### ISSUE TITLE
Setup Home Page

### ISSUE THREAD

**Issue by RSiferd2** [SweatyFigs/SweatyFigs#18] opened 2016-09-01 00:30 UTC

**Comment by brianzhou13** [comment] 2016-09-01 00:31
setting the html.

**Comment by brianzhou13** [comment] 2016-09-01 02:10
added code to index.html:
-included <div ng-view>
-added nav-bar

**Comment by brianzhou13** [comment] 2016-09-01 02:39
Seem to be a duplicate of 19...? but task is done.

**Closed** 2016-09-01 18:57 UTC
